### PR TITLE
Bug fix: decode TOML array of tables

### LINKED ISSUE #630: @ytt:toml.decode() fails to marshal TOML array of table values
reported: https://kubernetes.slack.com/archives/CH8KCCKA5/p1647400515157369
minimal example: https://carvel.dev/ytt/#gist:https://gist.github.com/pivotaljohn/81df98b1024374ca04ad30ad987cc70b
TOML docs:  https://toml.io/en/v1.0.0#array-of-tableshttps://toml.io/en/v1.0.0#array-of-tables

**Environment:**

- ytt version (use `ytt --version`): v0.40.1

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

### PR DESCRIPTION
**Pull request by gcheadle-vmware**
fixes: https://github.com/vmware-tanzu/carvel-ytt/issues/630

added `case []map[string]interface{}:` to conversion process.

### CODE REVIEW

File: pkg/orderedmap/convert.go [hunk 1]
```diff
@@ -74,7 +74,13 @@ func (c Conversion) fromUnorderedMaps(object interface{}) interface{} {
 			typedObj[i] = c.fromUnorderedMaps(item)
 		}
 		return typedObj
-
+	case []map[string]interface{}:
```
Comment (gcheadle-vmware) [inline pkg/orderedmap/convert.go:81]: Having the case `map[interface{}]interface{}:` earlier in this function makes me think that we should cover the  similar case: `[]map[interface{}]interface{}:`. However, I could not construct a TOML map with non 'string' map keys. 

Ultimately, I was left with this question: 
- "Why is the input of an array of maps not covered by the `[]interface{}` case?"

Comment (gcheadle-vmware) [reply pkg/orderedmap/convert.go:81]: Another way to ask the question:
- "Why does `toml.decode` return different types of slices rather than always returning `[]interface{}`" 

Found others hitting up against the `toml.Unmarshal` inconsistencies: https://github.com/BurntSushi/toml/issues/169

Comment (cppforlife) [inline pkg/orderedmap/convert.go:81]: nit (style): other cases have newline before/after them.

File: pkg/orderedmap/convert.go [hunk 2]
```diff
@@ -74,7 +74,13 @@ func (c Conversion) fromUnorderedMaps(object interface{}) interface{} {
...
+		resultArray := make([]interface{}, len(typedObj))
+		for i, item := range typedObj {
+			resultMap := c.fromUnorderedMaps(item)
```
Comment (cppforlife) [inline pkg/orderedmap/convert.go]: nit: do we need local variable here?

File: pkg/orderedmap/convert.go (hunk 1 above)
Comment (pivotaljohn) [inline pkg/orderedmap/convert.go:81]:
```suggestion

	// some sources (e.g. toml library) yield specific type of slices.
	// slices in Go are not covariant, so each flavor of slice must have its own case, here.
	// process these exactly the same way we do for generic slices (prior case)
	case []map[string]interface{}:
```

For now: Leave ourselves a note about why we have two cases with the same body.
Soon: we'll eventually upgrade to 1.18. At that point, we might be able to make this collection generic. 😁

**Review by pivotaljohn — APPROVED** [review]
LGTM.

In addition to @cppforlife's formatting nits, I'm suggesting a note to explain both where this specific type of slice is coming from and why we can't just combine all the cases... for now.

Thanks for tackling this one, @gcheadle-vmware.
