### PR TITLE
Optionally, `overlay/insert` via function

### LINKED ISSUE #718: Panics when appending to "empty"
**What steps did you take:**

``` yaml
#! dreams.yaml
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"name": "Sandman", "profession": "King of Dreams"})
#@overlay/append
---
name: Matthew
profession: Raven
```

```shell
ytt -f dreams.yaml
```

**What happened:**

```
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/vmware-tanzu/carvel-ytt/pkg/yttlibrary/overlay.Op.appendDocument(...)
        github.com/vmware-tanzu/carvel-ytt/pkg/yttlibrary/overlay/document.go:197
github.com/vmware-tanzu/carvel-ytt/pkg/yttlibrary/overlay.Op.applyDocSet({{0x148b260, 0xc0000aed08}, {0x1516700, 0xc0001595e0}, 0xc0001abd60, 0x0}, {0x19d9090, 0x1, 0x0}, 0xc0001595e0, ...)
        github.com/vmware-tanzu/carvel-ytt/pkg/yttlibrary/overlay/op.go:149 +0x805
github.com/vmware-tanzu/carvel-ytt/pkg/yttlibrary/overlay.Op.apply({{0x148b260, 0xc0000aed08}, {0x1516700, 0xc0001595e0}, 0xc0001abd60, 0x0}, {0x148b260, 0xc0000aed20}, {0x1516700, 0xc0001595e0}, ...)
        github.com/vmware-tanzu/carvel-ytt/pkg/yttlibrary/overlay/op.go:55 +0x35c
github.com/vmware-tanzu/carvel-ytt/pkg/yttlibrary/overlay.Op.Apply({{0x148b260, 0xc0000aed08}, {0x1516700, 0xc0001595e0}, 0xc0001abd60, 0x0})
        github.com/vmware-tanzu/carvel-ytt/pkg/yttlibrary/overlay/op.go:27 +0x14f
github.com/vmware-tanzu/carvel-ytt/pkg/workspace.OverlayPostProcessing.Apply({0xc0001b3a58})
        github.com/vmware-tanzu/carvel-ytt/pkg/workspace/overlay_post_processing.go:63 +0x716
github.com/vmware-tanzu/carvel-ytt/pkg/workspace.(*LibraryExecution).Eval(0xc0001b3a58, 0x0, {0x0, 0x0, 0xc0000ae5e8}, {0x0, 0xc0000a1960, 0x0})
        github.com/vmware-tanzu/carvel-ytt/pkg/workspace/library_execution.go:183 +0x7b
github.com/vmware-tanzu/carvel-ytt/pkg/cmd/template.(*Options).RunWithFiles(0xc0000db540, {{0xc0000b6100, 0x2, 0xc}}, {0x1689890, 0xc0001532f0})
        github.com/vmware-tanzu/carvel-ytt/pkg/cmd/template/cmd.go:164 +0x570
github.com/vmware-tanzu/carvel-ytt/pkg/cmd/template.(*Options).Run(0xc0000db540)
        github.com/vmware-tanzu/carvel-ytt/pkg/cmd/template/cmd.go:100 +0x4b7
github.com/vmware-tanzu/carvel-ytt/pkg/cmd.NewCmd.func1(0x0, {0xc0000ce9c0, 0x0, 0x0})
        github.com/vmware-tanzu/carvel-ytt/pkg/cmd/template.go:22 +0x1d
github.com/cppforlife/cobrautil.WrapRunEForCmd.func1.1(0x0, {0xc0000ce9c0, 0x0, 0x2})
        github.com/cppforlife/cobrautil@v0.0.0-20200514214827-bb86e6965d72/misc.go:45 +0x6d
github.com/cppforlife/cobrautil.WrapRunEForCmd.func1.1(0xc00013ea00, {0xc0000ce9c0, 0x0, 0x2})
        github.com/cppforlife/cobrautil@v0.0.0-20200514214827-bb86e6965d72/misc.go:45 +0x6d
github.com/spf13/cobra.(*Command).execute(0xc00013ea00, {0xc0000a2190, 0x2, 0x2})
        github.com/spf13/cobra@v1.5.0/command.go:872 +0x624
github.com/spf13/cobra.(*Command).ExecuteC(0xc00013ea00)
        github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
        github.com/vmware-tanzu/carvel-ytt/cmd/ytt/ytt.go:21 +0xd6
```

**What did you expect:**

A helpful error message.

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

**Environment:**

- ytt version (use `ytt --version`): `ytt version 0.42.0`
- OS (e.g. from `/etc/os-release`): macOS

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

### PR DESCRIPTION
**Pull request by mamachanko**
The insert overlay action has an optional 'via' kwarg, which receives the left and right node and produces the new right node, similar to the replace overlay action.

For example, this allows to add a `ConfigMap` into every matched Kubernetes `Namespace` without knowing their names in advance:

```yaml
#@ load("@ytt:overlay", "overlay")

#@ for i in range(3):
---
apiVersion: v1
kind: Namespace
metadata:
  name: #@ i
#@ end

#@ def cm(ns):
apiVersion: v1
kind: ConfigMap
metadata:
  name: insert
  namespace: #@ ns["metadata"]["name"]
#@ end

#@overlay/match by=overlay.subset({"kind": "Namespace"}), expects="0+"
#@overlay/insert after=True, via=lamda ns,_: cm(ns)
---
```
produces:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: 0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: insert
  namespace: 0
---
apiVersion: v1
kind: Namespace
metadata:
  name: 1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: insert
  namespace: 1
---
apiVersion: v1
kind: Namespace
metadata:
  name: 2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: insert
  namespace: 2
```

---

Addresses #738 

Qs for the maintainers:
* What do you think about the suggested API?
* @jtigger [mentioned](https://github.com/vmware-tanzu/carvel-ytt/issues/738#issuecomment-1239662734) that: _"the solution to this is likely to also resolve #718"_. However, I don't see how.
* `InsertAnnotation.Value` is mostly a reproduction of [ReplaceAnnotation.Value](https://github.com/vmware-tanzu/carvel-ytt/blob/develop/pkg/yttlibrary/overlay/replace_annotation.go#L57-L93) sans comments and todos. It felt not right to copy over those unless that is preferred.
* If `via=lambda ...` expects more than one arg it does not produce a great error message, much like `overlay/replace`'s via. For example: `overlay.apply: Document on line stdin:16: function lambda missing 2 arguments (...`  Would you consider improving that part of this PR?

Companion PR for docs: https://github.com/vmware-tanzu/carvel/pull/553

### CODE REVIEW

File: pkg/yttlibrary/overlay/insert_annotation.go [hunk 1]
```diff
@@ -36,20 +49,23 @@ func NewInsertAnnotation(newItem template.EvaluationNode) (InsertAnnotation, err
...
+		case InsertAnnotationKwargAfter:
 			resultBool, err := tplcore.NewStarlarkValue(kwarg[1]).AsBool()
 			if err != nil {
 				return InsertAnnotation{}, err
 			}
 			annotation.after = resultBool
 
+		case InsertAnnotationKwargVia:
+			annotation.via = &kwarg[1]
+
```
Comment (pivotaljohn) [inline pkg/yttlibrary/overlay/insert_annotation.go]: _(Commentary, not a request for a change, per se.)_

It's interesting that in `@overlay/replace` (and therefore here) we store the `via=` as a `starlark.Value` (rather than a `starlark.Callable`).
We also don't vet the argument, here — a natural choke-point for invalid input.

The advantage of vetting/constraining as early as possible is that it _generally_ simplifies subsequent logic, reducing complexity overall.

Since there's very little distance between `NewAssertionAnnotation()` and `Value()` (below), I don't see that complexity reduction: just moving code around.

It's more meaningful as aiming for exemplary code (i.e. worthy of imitation).

It's not the responsibility of the author of this PR to "fix" this; nor is this a blocker for this PR (that's impractical).

**Review by pivotaljohn — COMMENTED** [review]
> What do you think about the suggested API?

🤔 Any reason not to include the "right" value as an argument to `via=`?

It doesn't always come up, but doing so allows the author to highlight a YAML fragment as an important piece. e.g. resource limits that override a targeted PodSpec of some kind where the point is to replace them.

Doing so also makes it easier to re-use a function written for `@overlay/replace` with `@overlay/insert`.

Finally, it is consistent; one less thing to explain to authors.

Thoughts?

---

> @jtigger https://github.com/vmware-tanzu/carvel-ytt/issues/738#issuecomment-1239662734 that: "the solution to this is likely to also resolve https://github.com/vmware-tanzu/carvel-ytt/issues/718". However, I don't see how.

👎🏻 I was wrong about that. I assumed that since we were talking about inserting into an empty collection, that would have been part of the implementation, here. In fact, `@overlay/append` is not _merely_ an `@overlay/insert after=True`. 🤔💭 

---

> InsertAnnotation.Value is mostly a reproduction of [ReplaceAnnotation.Value](https://github.com/vmware-tanzu/carvel-ytt/blob/develop/pkg/yttlibrary/overlay/replace_annotation.go#L57-L93) sans comments and todos. It felt not right to copy over those unless that is preferred.

👍🏻  Yeah, the comments there don't seem to restore much (if any) context that the reader would already have.

---

> If via=lambda ... expects more than one arg it does not produce a great error message, much like overlay/replace's via. For example: overlay.apply: Document on line stdin:16: function lambda missing 2 arguments (... Would you consider improving that part of this PR?

👌🏻  I wouldn't consider it to be _required_ scope for this PR. `@overlay/replace via=` has behaved this way for years.

**Comment by pivotaljohn** [comment]
> Companion PR for docs: https://github.com/vmware-tanzu/carvel/pull/553

Wow! This is wonderful! 🙏🏻

File: pkg/yttlibrary/overlay/insert_annotation.go (hunk 1 above)
Comment (mamachanko) [reply pkg/yttlibrary/overlay/insert_annotation.go]: I have refactored both annotations to store their `via` kwarg as a `starklark.Callable`. To avoid regression, the error case for both are covered with a template test.

My first intuition was to extend `pkg.template.core.StarlarkValue` with a `AsCallable`, but that does not work because Go has no function type that is arg-agnostic, which is why we like Go. And so, I settled for a straight-forward type assertion within the `New*` constructor of each annotation.

**Comment by mamachanko** [comment]
@pivotaljohn As per your very reasonable suggestion, the `via` kwarg now receives both the left and the right node. 🙇🏻‍♂️

**Review by pivotaljohn — APPROVED** [review]
Hey @mamachanko, thanks for your patience as we cleared the decks with the v0.43.0 release. 🙇🏻‍♂️ 

I walked through the flow again; this all looks spot on.
You included some tidying up and we appreciate that as well.
Thank you for the added tests.

**Comment by mamachanko** [comment]
@pivotaljohn wonderful! 🥹 

You closed #718, but is it possible you meant to close #738 instead?

**Comment by pivotaljohn** [comment]
Oh wow... I think it was this comment that triggered the workflow: https://github.com/vmware-tanzu/carvel-ytt/issues/738#issuecomment-1239662734

I'll be choosing my words more wisely, going forward.
