### PR TITLE
Private lib schema

### LINKED ISSUE #296: Type check private library data values
**As a** Configuration Consumer using a private library
**I want** the set of data values supplied to the library to be subject to schema defined within the library.
**so that** when I misconfigure the library, I get specific, clear, and actionable feedback

---

### Scenario 1: Declarative Schema-Conforming Data Value

**Given** ytt input that includes a private library
**And** that private library contains schema
**And** a data values document targeting the private library that conforms to schema
**When** I invoke `ytt`
**Then** those data values are reflected in the evaluation of the private library

```
├── _ytt_lib
│   └── fooy
│       ├── schema.yml
│       └── template.yml
├── root.yml
└── values.yml
```

```yaml
#! fooy/schema.yml
#@schema/match data_values=True
---
foo: 42
```
```yaml
#! fooy/template.yml
#@ load("@ytt:data", "data")
---
foo: #@ data.values.foo
```
```yaml
#! root.yml
#@ load("@ytt:template", "template")
#@ load("@ytt:library", "library")
--- #@ template.replace(library.get("fooy").eval())
```
```yaml
#! values.yml
#@library/ref "@fooy"
#@data/values
---
foo: 7
```

```console
$ ytt -f . --enable-experiment-schema
foo: 7
```

### Scenario 2: Declarative Schema-Non-Conforming Data Value

**Given** ytt input that includes a private library
**And** that private library contains schema
**And** a data values document targeting the private library that does *NOT* conform to schema
**When** I invoke `ytt`
**Then** I see a schema error message in the context of a library evaluation error

```yaml
#! values.yml
#@library/ref "@fooy"
#@data/values
---
foo: "wrong type"
```
_(all other files are identical from prior scenario)_

```console
$ ytt -f .
ytt: Error:
- library.eval: Evaluating library 'fooy':
    in <toplevel>
      root.yml:3 | --- #@ template.replace(library.get("fooy").eval())

    reason:
Overlaying data values (in following order: values.yml):
  Templating file 'values.yml':
values.yml:5 | foo: wrong type
             |
             | TYPE MISMATCH - the value of this item is not what schema expected:
             |      found: string
             |   expected: integer (by schema.yml:4)
```

### Scenario 3: Programmatic Schema-Conforming Data Value

**Given** ytt input that includes a private library
**And** that private library contains schema
**And** a template in the root library supplies a data values document to the private library that conforms to the private library's schema
**When** I invoke `ytt`
**Then** those data values are reflected in the evaluation of the private library

```
.
├── _ytt_lib
│   └── fooy
│       ├── schema.yml
│       └── template.yml
└── root.yml
```

```
#! root.yml
#@ load("@ytt:template", "template")
#@ load("@ytt:library", "library")
---

#@ def dvs_from_root():
#@overlay/match missing_ok=True
foo: from "root" library
#@ end

--- #@ template.replace(library.get("fooy").with_data_values(dvs_from_root()).eval())
```

```
#! fooy/schema.yml
#@schema/match data_values=True
---
foo: ""
```

```
#! fooy/template.yml
#@ load("@ytt:data", "data")
---
foo: #@ data.values.foo
```

```console
$ ytt -f . --enable-experiment-schema
foo: from "root" library
```

### Scenario 4: Programmatic Schema-Non-Conforming Data Value

**Given** ytt input that includes a private library
**And** that private library contains schema
**And** a template in the root library supplies a data values document to the private library that does *NOT* conform to the private library's schema
**When** I invoke `ytt`
**Then** I see a schema error message in the context of a library evaluation error

```
#! root.yml
#@ load("@ytt:template", "template")
#@ load("@ytt:library", "library")
---

#@ def dvs_from_root():
#@overlay/match missing_ok=True
foo: 13
#@ end

--- #@ template.replace(library.get("fooy").with_data_values(dvs_from_root()).eval())
```
_(all other files are identical from prior scenario)_
```console
$ ytt -f .
ytt: Error:
- library.eval: Evaluating library 'fooy':
    in <toplevel>
      root.yml:10 | --- #@ template.replace(library.get("fooy").with_data_values(dvs_from_root()).eval())

    reason:
Overlaying data values (in following order: values.yml):
  Templating file 'values.yml':
root.yml:7 | foo: 13
             |
             | TYPE MISMATCH - the value of this item is not what schema expected:
             |      found: integer
             |   expected: string (by schema.yml:4)
```
_Note: the above error output is inaccurate due to the `values.yml` reference which is non-existent. We think it would `root.yml` in this case but haven't verified, yet._

### PR DESCRIPTION
**Pull request by pivotaljohn**
As part of this PR we decided on some UX decisions described below:
* When `--enable-experiement-schema` flag is **not** present, and a schema file is provided, a warning is shown. **New in this PR** the relative path to the file is also shown. (Consider the case where root library has a schema, and a private library has a schema, there will be **two** warning messages now).
* Rules around how the `--enable-experiement-schema` behaves: 
When the `--enable-experiement-schema` flag is present, and a schema file is given in the root or in a private library, it is used as the base data values and type checked.
When `--enable-experiement-schema` flag is **not** enabled, then if a schema file appears anywhere, the schema is IGNORED and a warning is given. This is because the schema flag is protecting the user against non-GA code.

⚠️   Update based on feedback ⚠️  
We decided to split this original PR into three separate ones.
```
develop 
|_overlay-position       <- PR to address position changes within overlay module (separate for this PR entirely)
|_ refactor-dvpp         <- PR to address refactoring done in data_values_pre_processing.go (must merge prior to this PR)
    |_ private-lib-schema <- this PR
```

### CODE REVIEW

**Comment by pivotaljohn** [comment]
> When --enable-experiement-schema flag is not enabled, then if a schema file appears anywhere, the schema is IGNORED and a warning is given. This is because the schema flag is protecting the user against non-GA code.

I really like this choice. It gives the author the ability to support _both_ modes. Include both a `schema.yml` and `values/default.yml` with basically the same content. If I enable schemas, I get the schema checks. If I don't I get the overlay checks.

File: pkg/yttlibrary/overlay/array.go [hunk 1]
```diff
@@ -43,6 +43,8 @@ func (o Op) mergeArrayItem(
 		}
 		if replace {
 			leftArray.Items[leftIdx].Value = newItem.Value
+			//todo: should we be setting the position elsewhere?
+			leftArray.Items[leftIdx].Position = newItem.Position
```
Comment (cppforlife) [inline pkg/yttlibrary/overlay/array.go]: can we keep position related improvements separate from this PR. it's a bit hard to tell if these are the only places where we need to change this -- would love to see holistic evaluation within overlay module.

File: pkg/cmd/template/cmd.go [hunk 2]
```diff
@@ -121,36 +120,20 @@ func (o *Options) RunWithFiles(in Input, ui ui.UI) Output {
...
 		ImplicitMapKeyOverrides: o.ImplicitMapKeyOverrides,
 		StrictYAML:              o.StrictYAML,
+		SchemaEnabled:           o.SchemaEnabled,
 	})
 
 	libraryCtx := workspace.LibraryExecutionContext{Current: rootLibrary, Root: rootLibrary}
 	libraryLoader := libraryExecutionFactory.New(libraryCtx)
 
-	schemaDocs, err := libraryLoader.Schemas()
+	currSchema, err := libraryLoader.Schemas()
```
Comment (cppforlife) [inline pkg/cmd/template/cmd.go]: is it worth renaming libraryLoader -> rootLibraryLoader

File: pkg/schema/schema.go [hunk 3]
```diff
@@ -73,10 +73,6 @@ func NewMapType(m *yamlmeta.Map) (*MapType, error) {
 		}
 		mapType.Items = append(mapType.Items, mapItemType)
 	}
-	annotations := template.NewAnnotations(m)
```
Comment (cppforlife) [inline pkg/schema/schema.go:76]: note for self: removed because it's dead code.

File: pkg/workspace/data_values_pre_processing.go [hunk 4]
```diff
@@ -37,46 +38,89 @@ func (o DataValuesPreProcessing) Apply() (*DataValues, []*DataValues, error) {
...
 
 func (o DataValuesPreProcessing) apply(files []*FileInLibrary) (*DataValues, []*DataValues, error) {
-	values := o.loader.schema.AsDataValue()
-	var libraryValues []*DataValues
-	for _, fileInLib := range files {
-		valuesDocs, err := o.templateFile(fileInLib)
-		if err != nil {
-			return nil, nil, fmt.Errorf("Templating file '%s': %s", fileInLib.File.RelativePath(), err)
-		}
+	_, checkSchema := o.loader.schema.(*schema.DocumentSchema)
```
Comment (cppforlife) [inline pkg/workspace/data_values_pre_processing.go]: something to think about... why do we need a boolean here? why cant we just tell schema to type check against itself. all schemas should be able to do it succesfully.

File: pkg/workspace/data_values_pre_processing.go [hunk 5]
```diff
@@ -37,46 +38,89 @@ func (o DataValuesPreProcessing) Apply() (*DataValues, []*DataValues, error) {
...
 
-		for _, valuesDoc := range valuesDocs {
-			dv, err := NewDataValues(valuesDoc)
+	allDvs, err := o.collectDataValuesDocs(files)
```
Comment (cppforlife) [inline pkg/workspace/data_values_pre_processing.go:41]: nice little refactor!

File: pkg/workspace/data_values_pre_processing.go [hunk 6]
```diff
@@ -37,46 +38,89 @@ func (o DataValuesPreProcessing) Apply() (*DataValues, []*DataValues, error) {
...
+	if err != nil {
+		return nil, nil, err
+	}
+
+	// merge all Data Values YAML documents into one
+	var dvsForOtherLibraries []*DataValues
+	var dataValuesDoc *yamlmeta.Document
```
Comment (cppforlife) [inline pkg/workspace/data_values_pre_processing.go]: i wonder if naming this from dataValuesDoc -> resultDVsDoc would make it a bit more readable. (it's the result from this loop)

File: pkg/workspace/data_values_pre_processing.go [hunk 7]
```diff
@@ -37,46 +38,89 @@ func (o DataValuesPreProcessing) Apply() (*DataValues, []*DataValues, error) {
...
+	for _, dv := range allDvs {
+		switch {
+		case dv.HasLibRef():
```
Comment (cppforlife) [inline pkg/workspace/data_values_pre_processing.go]: this switch statement could be made more readable as two if statements. note that type checking below switch statement would happen even if dvs are for a library ref with current impl.

```
if lib dvs {
   ...
   continue
}

if nil {
  ...
} else {
  ...
}
```

the fact that there is 2 if statements leads the reader to see that it's two unrelated pieces of functionality.

File: pkg/workspace/data_values_pre_processing.go [hunk 8]
```diff
@@ -37,46 +38,89 @@ func (o DataValuesPreProcessing) Apply() (*DataValues, []*DataValues, error) {
...
+			dvsForOtherLibraries = append(dvsForOtherLibraries, dv)
+		case dataValuesDoc == nil:
+			err := o.loader.schema.ValidateWithValues(1)
```
Comment (cppforlife) [inline pkg/workspace/data_values_pre_processing.go]: note to self: function goes away as soon as we kill experimental flag.

File: pkg/workspace/data_values_pre_processing.go [hunk 9]
```diff
@@ -37,46 +38,89 @@ func (o DataValuesPreProcessing) Apply() (*DataValues, []*DataValues, error) {
...
-			default:
-				var err error
-				values, err = o.overlay(values, dv.Doc)
-				if err != nil {
-					return nil, nil, err
-				}
+			dataValuesDoc = dv.Doc
+		default:
+			if checkSchema {
+				o.annotateWithDefaultMissingOk(dv.Doc)
```
Comment (cppforlife) [inline pkg/workspace/data_values_pre_processing.go]: let's pull this out as a separate PR. by adding missing_ok=True in certain cases we are affecting how overlay feature behaves under certain conditions. that's not desirable because we want users to know that same piece of code behaves same way regardless where it's being called from.

quick example that comes to mind: 
```
#@overlay/match by=overlay.subset({"name":"foo"})
- blah: something
```
will behave differently since since overlay module by default sets expects=1.

to start resolving this situtation, i think we need to figure out what happens in various interactions between schema and overlay. what errors would one expect to see when new keys are used, what errors do we expect to see when new keys are used with any type, etc.. let's have a document enumerating these cases and discuss them.

File: pkg/workspace/data_values_pre_processing.go [hunk 10]
```diff
@@ -37,46 +38,89 @@ func (o DataValuesPreProcessing) Apply() (*DataValues, []*DataValues, error) {
...
+			}
+			allDvs = append(allDvs, dv)
+		}
+	}
+	allDvs = append(allDvs, o.valuesOverlays...)
+	return allDvs, nil
+}
 
-	return dv, libraryValues, nil
+func (o DataValuesPreProcessing) typeAndCheck(dataValuesDoc *yamlmeta.Document) (chk yamlmeta.TypeCheck) {
```
Comment (cppforlife) [inline pkg/workspace/data_values_pre_processing.go]: we typically discourage use of named returns. dont think it's necessary in this case.

File: pkg/workspace/data_values_pre_processing.go [hunk 11]
```diff
@@ -37,46 +38,89 @@ func (o DataValuesPreProcessing) Apply() (*DataValues, []*DataValues, error) {
...
+	chk = o.loader.schema.AssignType(dataValuesDoc)
+	if len(chk.Violations) > 0 {
+		return
+	}
+
+	typeCheck := dataValuesDoc.Check()
+	chk.Violations = append(chk.Violations, typeCheck.Violations...)
```
Comment (cppforlife) [inline pkg/workspace/data_values_pre_processing.go]: no need to append to chk.Violations since it's guranteed to be 0.

File: pkg/workspace/data_values_pre_processing.go (hunk 4 above)
Comment (cppforlife) [inline pkg/workspace/data_values_pre_processing.go]: accessing private data from loader got me curious... it seems that template loader does not use schema at all. it seems weird for template loader to know anything about schema since it's not dealing with data values. i would have expected DataValuesPreProcessing to be initialized with appropriate schema.

File: pkg/workspace/data_values_pre_processing.go [hunk 12]
```diff
@@ -151,30 +178,23 @@ func (o DataValuesPreProcessing) overlay(valuesDoc, newValuesDoc *yamlmeta.Docum
...
-	for _, valuesOverlay := range o.valuesOverlays {
-		var err error
-
-		result, err = o.overlay(result, valuesOverlay.Doc)
-		if err != nil {
-			// TODO improve error message?
-			return nil, fmt.Errorf("Overlaying additional data values on top of "+
-				"data values from files (marked as @data/values): %s", err)
-		}
+func (o DataValuesPreProcessing) NewEmptyDataValuesDocument() *yamlmeta.Document {
```
Comment (cppforlife) [inline pkg/workspace/data_values_pre_processing.go]: seems like this method could be inlined where it's used, or at least made private.

File: pkg/workspace/library_loader.go [hunk 13]
```diff
@@ -46,30 +46,36 @@ func NewLibraryLoader(libraryCtx LibraryExecutionContext,
 	}
 }
 
-func (ll *LibraryLoader) Schemas() ([]*yamlmeta.Document, error) {
+func (ll *LibraryLoader) Schemas() (Schema, error) {
```
Comment (cppforlife) [inline pkg/workspace/library_loader.go]: if we are returning a single schema should this method be named Schema() as well?

File: pkg/workspace/library_loader.go [hunk 14]
```diff
@@ -46,30 +46,36 @@ func NewLibraryLoader(libraryCtx LibraryExecutionContext,
...
-		}
+			_, resultDocSet, err := loader.EvalYAML(libraryCtx, schemaFiles[0].File)
+			if err != nil {
+				return nil, err
+			}
 
-		docs, _, err := DocExtractor{resultDocSet}.Extract(AnnotationSchemaMatch)
-		if err != nil {
-			return nil, err
+			docs, _, err := DocExtractor{resultDocSet}.Extract(AnnotationSchemaMatch)
```
Comment (cppforlife) [inline pkg/workspace/library_loader.go:65]: if we get multiple schema docs i would expect that we would blow up for now since we do not allow merging schemas.

File: pkg/workspace/library_module.go [hunk 15]
```diff
@@ -318,7 +317,8 @@ func (l *libraryValue) libraryValues(ll *LibraryLoader) (*DataValues, []*DataVal
 		}
 	}
 
-	dvs, foundChildDVss, err := ll.Values(append(dvss, afterLibModDVss...), &schema.AnySchema{})
+	schema, err := ll.Schemas()
```
Comment (cppforlife) [inline pkg/workspace/library_module.go]: missing err check.

File: pkg/workspace/library_module.go [hunk 16]
```diff
@@ -318,7 +317,8 @@ func (l *libraryValue) libraryValues(ll *LibraryLoader) (*DataValues, []*DataVal
...
+	dvs, foundChildDVss, err := ll.Values(append(dvss, afterLibModDVss...), schema)
```
Comment (cppforlife) [inline pkg/workspace/library_module.go]: it seems that we are using ll.Schemas() and then passing it to ll.Values(). i would argue Values() shouldnt require schema as input and should just use ll.Schemas() internally.

File: pkg/yttlibrary/overlay/array.go (hunk 1 above)
Comment (pivotaljohn) [reply pkg/yttlibrary/overlay/array.go]: ... yup and that PR would precede this one — this fix addresses an actual bug: the wrong file is attributed a value.

File: pkg/workspace/data_values_pre_processing.go (hunk 12 above)
Comment (pivotaljohn) [reply pkg/workspace/data_values_pre_processing.go]: ... in part because there's no need for any code outside this module to generate an empty Data Values.

File: pkg/workspace/data_values_pre_processing.go (hunk 9 above)
Comment (pivotaljohn) [reply pkg/workspace/data_values_pre_processing.go]: ... and to clarify, it's not so much that we'd pull this out as a separate PR... but that we'd _either_:

- address this problem _within_ this PR, or,
- temporarily accept this intermediate state where it generally works but has undesired side-effects in some cases... but then _immediately_ address this problem in a subsequent PR.  (consider this change set "large enough" and address this as a separate unit of work)

But either way, we can't remove the `--enable-experiment-schemas` flag until we ensure that this works exact the way we want it.

File: pkg/workspace/data_values_pre_processing.go (hunk 6 above)
Comment (pivotaljohn) [reply pkg/workspace/data_values_pre_processing.go]: ... and taking that suggestion a step further, if we use the same naming scheme across identifiers: `(qualifier)(noun)`, the eye parses identifiers using the same pattern matcher, reducing cognitive load.

Example:
- `allDvs`
- `otherLibraryDvs`
- `resultDvDoc`
- others?

File: pkg/workspace/library_loader.go (hunk 14 above)
Comment (cari-lynn) [reply pkg/workspace/library_loader.go:65]: Correct, we have a story coming up to allow multiple schema docs #294. Prior to this story we would also blow up if we get multiple docs, so we haven't added guards for that case.

File: pkg/workspace/library_module.go (hunk 15 above)
Comment (cari-lynn) [reply pkg/workspace/library_module.go]: 😨

File: pkg/workspace/data_values_pre_processing.go (hunk 9 above)
Comment (cari-lynn) [reply pkg/workspace/data_values_pre_processing.go]: We pulled out this to a separate PR where it is addressed, @cppforlife ready for review. The PR is #337 and is a prerequisite to this work so that PR must be merged in prior to this one.

File: pkg/yttlibrary/overlay/array.go (hunk 1 above)
Comment (cari-lynn) [reply pkg/yttlibrary/overlay/array.go]: These position changes are now necessary to report the position of the overlay in the schema error message, if it's acceptable, we want to keep the change made to the position of arrays and maps here in [this](https://github.com/vmware-tanzu/carvel-ytt/pull/337) PR, and then address this more comprehensively in the [Overlay Positions](https://github.com/vmware-tanzu/carvel-ytt/pull/341) PR.
